version: '3'
services:
  sut:
    env_file:
      - .env
    build:
      context: .
      args:
        jdbc_driver_version: ${jdbc_driver_version}
    command: /opt/test_liquibase_postgres/run_test.sh
    environment:
      LIQUIBASE_HOST: localhost
    image: liquibase-postgres:build
